### ISSUE TITLE
what i missing in my python3 ubuntu 20 env?

### ISSUE THREAD

**Issue by johnfelipe** [bytedance/piano_transcription#10]
root@1-ubuntu-s-8vcpu-16gb-nyc1-01:~/piano_transcription# pip install -r requirements.txt
    Collecting h5py==2.10.0
      Using cached h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
    Collecting pandas==1.1.2
      Downloading pandas-1.1.2-cp38-cp38-manylinux1_x86_64.whl (10.4 MB)
         |████████████████████████████████| 10.4 MB 14.8 MB/s
    Collecting librosa==0.6.0
      Downloading librosa-0.6.0.tar.gz (1.5 MB)
         |████████████████████████████████| 1.5 MB 69.6 MB/s
    Collecting numba==0.48
      Downloading numba-0.48.0-1-cp38-cp38-manylinux2014_x86_64.whl (3.6 MB)
         |████████████████████████████████| 3.6 MB 67.2 MB/s
    Collecting mido==1.2.9
      Downloading mido-1.2.9-py2.py3-none-any.whl (52 kB)
         |████████████████████████████████| 52 kB 2.6 MB/s
    Collecting mir_eval==0.5
      Downloading mir_eval-0.5.tar.gz (86 kB)
         |████████████████████████████████| 86 kB 11.1 MB/s
    Collecting matplotlib==3.0.3
      Downloading matplotlib-3.0.3.tar.gz (36.6 MB)
         |████████████████████████████████| 36.6 MB 36.4 MB/s
        ERROR: Command errored out with exit status 1:
         command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m3wp3r8i/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m3wp3r8i/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-m3wp3r8i/matplotlib/pip-egg-info
             cwd: /tmp/pip-install-m3wp3r8i/matplotlib/
        Complete output (51 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-m3wp3r8i/matplotlib/setup.py", line 225, in <module>
            msg = pkg.install_help_msg()
          File "/tmp/pip-install-m3wp3r8i/matplotlib/setupext.py", line 650, in install_help_msg
            release = platform.linux_distribution()[0].lower()
        AttributeError: module 'platform' has no attribute 'linux_distribution'
        IMPORTANT WARNING:
            pkg-config is not installed.
            matplotlib may not be able to find some of its dependencies
        ============================================================================
        Edit setup.cfg to change the build options
    
        BUILDING MATPLOTLIB
                    matplotlib: yes [3.0.3]
                        python: yes [3.8.5 (default, May 27 2021, 13:30:53)  [GCC
                                9.3.0]]
                      platform: yes [linux]
    
        REQUIRED DEPENDENCIES AND EXTENSIONS
                         numpy: yes [version 1.18.5]
              install_requires: yes [handled by setuptools]
                        libagg: yes [pkg-config information for 'libagg' could not
                                be found. Using local copy.]
                      freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                                could not be found.  You may need to install the
                                development package.]
                           png: no  [pkg-config information for 'libpng' could not
                                be found.]
                         qhull: yes [pkg-config information for 'libqhull' could not
                                be found. Using local copy.]
    
        OPTIONAL SUBPACKAGES
                   sample_data: yes [installing]
                      toolkits: yes [installing]
                         tests: no  [skipping due to configuration]
                toolkits_tests: no  [skipping due to configuration]
    
        OPTIONAL BACKEND EXTENSIONS
                           agg: yes [installing]
                         tkagg: yes [installing; run-time loading from Python Tcl /
                                Tk]
                        macosx: no  [Mac OS-X only]
                     windowing: no  [Microsoft Windows only]
    
        OPTIONAL PACKAGE DATA
                          dlls: no  [skipping due to configuration]
    
        ============================================================================
                                * The following required packages can not be built:
                                * freetype, png
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lzh88998** [comment]
ensure you are using python 3.7. There are some problems with matplotlib in python 3.8
