### ISSUE TITLE
Librosa problem

### ISSUE THREAD

**Issue by NikolasHofmann** [bytedance/piano_transcription#38]
Hey :),
I cloned the repository and followed the steps you provided, using python 3.7 and installed everything from requirements.txt. I am running pretty much the example easy-use python code you provided, just with a different piano audio file. I am getting this here (I am a beginner). Any ideas?

Traceback (most recent call last):
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/nikolas.py", line 1, in <module>
    from piano_transcription_inference import PianoTranscription, sample_rate, load_audio
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/piano_transcription_inference/__init__.py", line 1, in <module>
    from .inference import PianoTranscription
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/piano_transcription_inference/inference.py", line 4, in <module>
    import librosa
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/librosa/core/__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/librosa/util/utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "/media/nikolas/D_HDD/code_hdd/piano_transcription/.venv/lib/python3.7/site-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
AttributeError: 'CacheManager' object has no attribute 'cachedir'

**Comment by BOURBON0** [comment]
hi~, I meet the same problem. have you solved it?

**Comment by surfissh** [comment]
Same issue.

**Comment by surfissh** [comment]
The correct librosa version should be 0.7.0. It works well on my machine now.
